### ISSUE TITLE
删除机构或模块的问题

### ISSUE THREAD

**Issue by wujng68** [ketayao/keta-custom#13]
当删除没有子节点的机构或模块时，系统提示删除成功了，但其实没删除。

**Comment by sundful** [comment]
我也遇到这样的问题，请尽快解决！~

**Comment by sundful** [comment]
有的时候能删除，但是几率很小！~用户删除，角色删除没有问题！~

**Comment by wujng68** [comment]
如果在机构、模块实体中将自关联的子集 @oneToMany中的mappeby="parent"删掉 就好了。但这样不知道会不会引起其他问题。

**Comment by ketayao** [comment]
由于在生成环境中，模块和组织很少修改删除，启用了查询缓存，所以会造成数据不一致，清空缓存就ok了。

**Comment by wujng68** [comment]
问题已解决，是级联的问题

**Comment by sundful** [comment]
问题解决了？怎么解决的？

**Comment by ketayao** [comment]
该bug已解决，将在新版本中发布。
