### ISSUE TITLE
角色授权模块的展示方式能全换成树形机构就好了，checkbox多了页面不好展示

### ISSUE THREAD

**Issue by wangjunahaq** [ketayao/keta-custom#18]
希望能把对应权限显示在对应模块的下级树上，这样授权比较直观，权限多了也不会影响 页面的排版

如果把权限和模块菜单集成到一张表中，只是用模块类型来区分，这样做起来是不是更方便点呢？我的理解是模块菜单其实也是一种权限的。放到一起做成树形结构的授权模式感觉会比较好

**Comment by ketayao** [comment]
已解决。
