### ISSUE TITLE
换皮肤后搜索模块跟头顶上的提示窗口颜色没换上

### ISSUE THREAD

**Issue by llinfish** [ketayao/keta-custom#2]

**Comment by ketayao** [comment]
这个是dwz本身的样式问题，看了看它的css文件，主要是相应的图片没有替换。多主题的功能，dwz本身做的不是很完善，所以不会放太多的精力去处理，如果嫌麻烦可以屏蔽多主题选择项，假如你完善了该功能，可以pull代码给我哦！
