### ISSUE TITLE
编辑角色的时候，在ie8中，所有的checkbox不显示出来

### ISSUE THREAD

**Issue by chpf3340** [ketayao/keta-custom#8]
编辑角色的时候，在ie8中，所有的checkbox不显示出来

**Comment by ketayao** [comment]
将在下个版本解决

**Comment by chpf3340** [comment]
非常感谢，坐等发布 

---

  海内存知己，天涯若比邻。

 ------------------ 原始邮件 ------------------
  发件人: "ketayao"notifications@github.com;
 发送时间: 2013年5月26日(星期天) 晚上6:05
 收件人: "ketayao/keta-custom"keta-custom@noreply.github.com; 
 抄送: "chpf3340"chpf3340@qq.com; 
 主题: Re: [keta-custom] 编辑角色的时候，在ie8中，所有的checkbox不显示出来 (#8)

将在下个版本解决
