### ISSUE TITLE
建议增加记录批量删除

### ISSUE THREAD

**Issue by chpf3340** [ketayao/keta-custom#9]
建议增加记录批量删除

**Comment by ketayao** [comment]
会在下个版本中，增强该功能。

**Comment by sundful** [comment]
支持该功能，现在只能自己先开发这个功能了！~

**Comment by chpf3340** [comment]
## 要我们自己来开发吗？ 

海内存知己，天涯若比邻。

------------------ 原始邮件 ------------------
发件人: "sundful"; 
发送时间: 2013年5月20日(星期一) 晚上6:06
收件人: "ketayao/keta-custom"; 
抄送: "chpf3340"; 
主题: Re: [keta-custom] 建议增加记录批量删除 (#9)

支持该功能，现在只能自己先开发这个功能了！~

&mdash;

**Comment by sundful** [comment]
我的意思是，我等不到下个版本发布，我有这个需求，我要自己开发该功能！~

在 2013-05-20 18:08:09，chpf3340 notifications@github.com 写道：

## 要我们自己来开发吗？

海内存知己，天涯若比邻。

------------------ 原始邮件 ------------------
发件人: "sundful";
发送时间: 2013年5月20日(星期一) 晚上6:06
收件人: "ketayao/keta-custom";
抄送: "chpf3340";
主题: Re: [keta-custom] 建议增加记录批量删除 (#9)

支持该功能，现在只能自己先开发这个功能了！~

&mdash;

**Comment by ketayao** [comment]
下个版本在6月前发布，快了还有几天。

**Comment by chpf3340** [comment]
谢谢，坐等发布 

---

  海内存知己，天涯若比邻。

 ------------------ 原始邮件 ------------------
  发件人: "ketayao"notifications@github.com;
 发送时间: 2013年5月26日(星期天) 下午5:41
 收件人: "ketayao/keta-custom"keta-custom@noreply.github.com; 
 抄送: "chpf3340"chpf3340@qq.com; 
 主题: Re: [keta-custom] 建议增加记录批量删除 (#9)

下个版本在6月前发布，快了还有几天。
